name: Send Newsletter

on:
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    env:
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      TEST_RECIPIENT: ${{ secrets.TEST_RECIPIENT }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          cache: maven

      - name: Build project
        run: mvn clean package

      - name: Execute newsletter
        run: mvn exec:java -Dexec.mainClass="br.com.gbnews.App"
